version: "3.7"

services:
  service:
    build: ./
    restart: always
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
    entrypoint: wait-for db:5432 -- ./entrypoint.sh
    ports:
      - 8000:80
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
    - ./postgres_data:/var/lib/postgresql/data:cached
    restart: always
    environment:
        POSTGRES_DB: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
    ports:
      - 15432:5432
